name: rebuilder
description: UI extensions for Value package

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  value:
    git: https://github.com/naviter/value

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
