name: rebuilder
description: A new Flutter package project.

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  value:
    git: https://github.com/naviter/value

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
